konbini/auth.py
from . import core
from functools import wraps
from .forms import EmailForm
from .util import send_email
from flask import current_app, flash, request, render_template
from itsdangerous import URLSafeTimedSerializer, SignatureExpired, BadSignature


def auth_required(fn):
    @wraps(fn)
    def decorated(*args, **kwargs):
        endpoint = request.endpoint
        token = request.args.get('token', None)
        ser = URLSafeTimedSerializer(
            secret_key=current_app.config['SECRET_KEY'],
            salt=current_app.config['SALT'])

        if token is None:
            return authenticate(ser, endpoint)

        # Valid for 1 hour
        email, expired, invalid = deserialize_token(ser, token, 3600)
        if expired:
            flash('Link expired. Please request a new one.')
        elif invalid:
            flash('Invalid link. Please request a new one.')
        ok = not expired and not invalid

        if not ok:
            return authenticate(ser, endpoint)
        return fn(email, *args, **kwargs)
    return decorated


def generate_token(serializer, text):
    return serializer.dumps(text)


def deserialize_token(serializer, name, max_age=None):
    try:
        return serializer.loads(name, max_age=max_age), False, False
    except SignatureExpired:
        return None, True, False
    except BadSignature:
        return None, False, True
    return None, False, False


def authenticate(ser, route):
    form = EmailForm()
    if form.validate_on_submit():
        email = form.email.data
        customers = core.get_customers(email)
        if not customers:
            flash('No account found with that email.')
        else:
            token = generate_token(ser, email)
            send_email([email],
                    '{} email confirmation'.format(current_app.config['SHOP_NAME']),
                    'auth', token=token, route=route)
            flash('Email sent to {}'.format(email))
    return render_template('shop/auth.html', form=form)

konbini/routes.py
import math
import stripe
from . import core, shipping
from .util import send_email
from .auth import auth_required
from .forms import EmailForm, ShippingForm
from pyusps import address_information
from urllib.parse import urlparse, urljoin
from flask import Blueprint, render_template, redirect, request, session, abort, url_for, flash, current_app, jsonify

USPS_ADDRESS_KEYS = {
    'address': 'line1',
    'address_extended': 'line2',
    'state': 'state',
    'city': 'city',
    'zip5': 'postal_code'
}

bp = Blueprint('shop', __name__, template_folder='templates')


def is_in_stock(sku):
    return sku.metadata.get('sold_out') != 'true'

def is_safe_url(target):
    ref_url = urlparse(request.host_url)
    test_url = urlparse(urljoin(request.host_url, target))
    return test_url.scheme in ('http', 'https') and \
           ref_url.netloc == test_url.netloc

def normalize_address(address):
    """Normalize a domestic (US) address"""
    if address['country'] != 'US':
        return address, False

    addr = {
        'zip_code': address['postal_code'],
        'state': address['state'],
        'city': address['city'],
        'address': address['line1']
    }
    line2 = address.get('line2')
    if line2:
        addr['address_extended'] = line2
    try:
        usps_addr = address_information.verify(current_app.config['USPS_USER_ID'], addr)
        norm_addr = {}
        changed = False
        for k_frm, k_to in USPS_ADDRESS_KEYS.items():
            norm_addr[k_to] = usps_addr.get(k_frm)
            if (norm_addr[k_to] or '').lower() != (address[k_to] or '').lower():
                changed = True
        norm_addr['country'] = 'US'
        return norm_addr, changed
    except ValueError:
        return None, True

@bp.route('/')
def index():
    products = core.get_products()
    if request.args.get('format') == 'json':
        return jsonify(products=products)
    else:
        return render_template('shop/index.html', products=products)

@bp.route('/product/<id>')
def product(id):
    id = 'prod_{}'.format(id)
    try:
        product = stripe.Product.retrieve(id, expand=['default_price'])
    except stripe.error.InvalidRequestError as err:
        current_app.logger.debug(str(err))
        abort(404)
    if product is None or not product.active: abort(404)
    if product.type == 'good':
        skus = stripe.SKU.list(limit=100, product=id, active=True)['data']
        images = product.images + [s.image for s in skus if s.image and s.image not in product.images]
        for sku in skus:
            sku['in_stock'] = is_in_stock(sku)
        if request.args.get('format') == 'json':
            return jsonify(product=product, skus=skus, images=images)
        else:
            return render_template('shop/product.html', product=product, skus=skus, images=images)
    else:
        prices = stripe.Price.list(limit=100, product=id, active=True)['data']
        if request.args.get('format') == 'json':
            return jsonify(product=product, prices=prices, images=product.images)
        else:
            return render_template('shop/product.html', product=product, prices=prices, images=product.images)


@bp.route('/cart', methods=['GET', 'POST'])
def cart():
    if request.method == 'GET':
        subtotal = sum((int(session['meta'][id]['price']) * q for id, q in session.get('cart', {}).items() if q), 0)
        return render_template('shop/cart.html', subtotal=subtotal)

    name = request.form['name']
    sku_id = request.form['sku']
    product_id = request.form['product']
    quantity = request.form.get('quantity')
    if quantity and quantity is not None:
        quantity = int(quantity)

    if 'cart' not in session:
        session['cart'] = {}

    # If no quantity specified, add one
    if quantity is None:
        added = True
        session['cart'][sku_id] = session['cart'].get(sku_id, 0) + 1
    else:
        added = False
        session['cart'][sku_id] = quantity

    if 'meta' not in session:
        session['meta'] = {}

    # Delete item from cart if quantity is 0
    if quantity == 0 or quantity == '':
        del session['cart'][sku_id]

    # Otherwise, update product info
    else:
        if sku_id.startswith('sku_'):
            sku = stripe.SKU.retrieve(sku_id)
            price = sku.price
            interval = None
            interval_count = None
            exclude_tax = sku.metadata.get('exclude_tax') == 'true'
        elif sku_id.startswith('price_'):
            sku = stripe.Price.retrieve(sku_id)
            exclude_tax = sku.metadata.get('exclude_tax') == 'true'
            price = sku.unit_amount
            if sku.recurring:
                interval = sku.recurring.interval
                interval_count = sku.recurring.interval_count
            else:
                interval = None
                interval_count = None

        session['meta'][sku_id] = {
            'name': name,
            'price': price,
            'interval': interval,
            'interval_count': interval_count,
            'product_id': product_id,
            'exclude_tax': exclude_tax,
        }

    if added:
        flash('Added "{}" to cart.'.format(name), category='cart')
    else:
        flash('Cart updated.')

    if is_safe_url(request.referrer):
        return redirect(request.referrer)
    return redirect(url_for('shop.index'))

@bp.route('/checkout', methods=['GET', 'POST'])
def checkout():
    if not session.get('cart'):
        return redirect(url_for('shop.index'))

    form = ShippingForm()
    if not current_app.config.get('KONBINI_INTL_SHIPPING'):
        form.address.country.data = 'US'
        form.address.country.validators = []

    if form.validate_on_submit():
        session['email'] = form.data['email']
        address = {k: form.data['address'][k] for k in
                   ['line1', 'line2', 'city', 'state', 'postal_code', 'country']}
        address, changed = normalize_address(address)
        if address is None:
            return render_template('shop/shipping.html', form=form, invalid_address=True)

        session['shipping'] = {
            'name': form.data['name'],
            'address': address
        }

        return redirect(url_for('shop.pay', address_changed=True))
    return render_template('shop/shipping.html', form=form)

@bp.route('/checkout/pay')
def pay():
    if not session.get('shipping'):
        return redirect(url_for('shop.cart'))

    # Sort out print on demand products before sending them to calculate shipping rate
    items = []
    shipper_products = dict((el,[]) for el in current_app.config.get('KONBINI_SHIPPERS'))
    default_shipper = current_app.config.get('KONBINI_DEFAULT_SHIPPER')
    for sku_id, q in session['cart'].items():
        p = stripe.Product.retrieve(session['meta'][sku_id]['product_id'], expand=['default_price'])
        shipper = p.metadata.get('shipper')
        if shipper is not None:
            shipper = shipper.lower()
        shipper_products[shipper].append((p,q)) if shipper else shipper_products[default_shipper].append((p,q))

        items.append({
            'currency': 'usd',
            'name': session['meta'][sku_id]['name'],
            'amount': session['meta'][sku_id]['price'],
            'quantity': q,
            'exclude_tax': session['meta'][sku_id]['exclude_tax'],
        })

    # calculate shipping rates for every shipper
    order_meta, total_shipping_rate = {'shippers':[]}, 0
    for shipper, products in shipper_products.items():
        if products:
            rate, shipper_meta = shipping.get_shipping_rate(products, session['shipping'], shipper, **current_app.config)
            order_meta.update(shipper_meta)
            order_meta['shippers'].append(shipper)
            total_shipping_rate += rate
    order_meta['shippers'] = " ".join(order_meta['shippers'])

    # if rpi returns an error then show a sorry page
    if order_meta.get('rpi_error'):
        return render_template('shop/sorry.html', products=shipper_products['rpi'])

    for k, v in session['shipping']['address'].items():
        order_meta['address_{}'.format(k)] = v
    order_meta['name'] = session['shipping']['name']

    items.append({
        'currency': 'usd',
        'name': 'Shipping',
        'amount': total_shipping_rate,
        'quantity': 1,
        'exclude_tax': True
    })

    total = sum(i['amount']*i['quantity'] for i in items)
    tax_total = sum(i['amount']*i['quantity'] for i in items if not i['exclude_tax'])

    # Can't pass this to the session
    for i in items:
        del i['exclude_tax']

    tax_rates = stripe.TaxRate.list(limit=10)
    for tax in tax_rates:
        if tax['jurisdiction'] == session['shipping']['address']['state']:
            items.append({
                'name': 'Tax',
                'amount': math.ceil((tax.percentage/100) * tax_total),
                'currency': 'usd',
                'quantity': 1
            })

    kwargs = {
        'payment_method_types': ['card'],
        'line_items': items,
        'success_url': url_for('shop.checkout_success', _external=True),
        'cancel_url': url_for('shop.checkout_cancel', _external=True),
        'metadata': order_meta
    }
    # Try to find customer with existing email
    customers = core.get_customers(session['email'])
    if customers:
        kwargs['customer'] = customers[0].id
    else:
        kwargs['customer_email'] = session['email']

    address_changed = request.args.get('address_changed')
    session['stripe'] = stripe.checkout.Session.create(**kwargs)

    return render_template('shop/pay.html',
            total=total,
            items=items,
            shipping=session['shipping'],
            address_changed=address_changed)

@bp.route('/checkout/success')
def checkout_success():
    for k in ['cart', 'plan', 'stripe', 'shipping']:
        if k in session: del session[k]
    return render_template('shop/thanks.html')

@bp.route('/checkout/cancel')
def checkout_cancel():

konbini/shipping/__init__.py
import importlib
from flask import current_app

def get_shipping_rate(products, addr, shipper, **config):
    shipper_module = importlib.import_module('.' + shipper, 'konbini.shipping')
    return shipper_module.get_shipping_rate(products, addr, **config)

def buy_shipment(shipper, **kwargs):
    shipper_module = importlib.import_module('.' + shipper, 'konbini.shipping')
    return shipper_module.buy_shipment(**kwargs)

def shipment_exists(shipment_id, shipper):
    shipper_module = importlib.import_module('.' + shipper, 'konbini.shipping')
    return shipper_module.shipment_exists(shipment_id)

def confirmation_email_text(shipper, **kwargs):
    shipper_module = importlib.import_module('.' + shipper, 'konbini.shipping')
    return shipper_module.confirmation_email(**kwargs)

konbini/templates/shop/_macros.html
{% macro render_field_with_errors(field, hint, label=True) %}
  <div class="form-field">
    {% if field.type != 'BooleanField' %}
        {% if label %} {{ field.label }} {% endif %} {{ field(**kwargs)|safe }}
    {% else %}
        {{ field(**kwargs)|safe }}
        {% if label %}{{ field.label }}{% endif %}
    {% endif %}
    {% if field.errors %}
      <ul class="errors">
      {% for error in field.errors %}
        <li class="error">{{ error|safe }}</li>
      {% endfor %}
      </ul>
    {% endif %}
    {% if hint %}
        <div class="form-field-hint muted">{{ hint }}</div>
    {% endif %}
  </div>
{% endmacro %}

{% macro render_field(field) %}
  {{ field(**kwargs)|safe }}
{% endmacro %}

konbini/templates/shop/_stripe.html
<script src="https://js.stripe.com/v3/"></script>
<script>
    {% if session['stripe']['id'] %}
        let checkoutButton = document.getElementById('js-pay');
        if (checkoutButton) {
            const stripe = Stripe('{{ config.STRIPE_PUBLIC_KEY }}');
            checkoutButton.addEventListener('click', () => {
                stripe.redirectToCheckout({
                    sessionId: '{{ session['stripe']['id'] }}',
                }).then(function (result) {
                    let flash = document.createElement('li');
                    flash.innerText = result.error.message;
                    flash.className = 'error';
                    document.getElementById('flashes').appendChild(flash);
                });
            });
        }
    {% endif %}
</script>

konbini/templates/shop/auth.html
{% from "shop/_macros.html" import render_field_with_errors %}
{% extends 'layout.html' %}

{% block content %}
<div class="authenticate">
    <h2>Confirm Email</h2>
    <form method="POST">
        {{ form.hidden_tag() }}
        {{ render_field_with_errors(form.email) }}
        <div class="actions">
            <input type="submit" value="Send Confirmation">
        </div>
    </form>
</div>
{% endblock %}

konbini/templates/shop/billing.html
{% extends 'layout.html' %}

{% block content %}
<div class="billing checkout">
    <h2>Update Billing Information</h2>
    <h3>for {{ email }}</h3>
    <form method="post" id="payment-form">
    <div class="form-row">
        <label for="card-element">
        Credit or debit card
        </label>
        <div id="card-element">
        </div>

        <div id="card-errors" role="alert"></div>
    </div>

    <button>Submit</button>
    </form>
</div>
<script src="https://js.stripe.com/v3/"></script>
<script>
const stripe = Stripe('{{ config.STRIPE_PUBLIC_KEY }}');
const elements = stripe.elements();
const card = elements.create('card');
card.mount('#card-element');

card.addEventListener('change', function(event) {
  var displayError = document.getElementById('card-errors');
  if (event.error) {
    displayError.textContent = event.error.message;
  } else {
    displayError.textContent = '';
  }
});

var form = document.getElementById('payment-form');
form.addEventListener('submit', function(event) {
  event.preventDefault();

  stripe.createToken(card).then(function(result) {
    if (result.error) {
      // Inform the user if there was an error.
      var errorElement = document.getElementById('card-errors');
      errorElement.textContent = result.error.message;
    } else {
      // Send the token to your server.
      stripeTokenHandler(result.token);
    }
  });
});

// Submit the form with the token ID.
function stripeTokenHandler(token) {
  // Insert the token ID into the form so it gets submitted to the server
  var form = document.getElementById('payment-form');
  var hiddenInput = document.createElement('input');
  hiddenInput.setAttribute('type', 'hidden');
  hiddenInput.setAttribute('name', 'stripeToken');
  hiddenInput.setAttribute('value', token.id);
  form.appendChild(hiddenInput);

  // Submit the form
  form.submit();
}
</script>
{% endblock %}

konbini/templates/shop/cart.html
{% extends 'layout.html' %}

{% macro set_quantity(icon, sku, name, product, quantity) %}
    <form class="cart--update-quantity" action="{{ url_for('shop.cart') }}" method="POST">
        <input type='hidden' name='sku' value={{ sku }}>
        <input type='hidden' name='name' value={{ name }}>
        <input type='hidden' name='product' value={{ product }}>
        <input type='hidden' name='quantity' value={{ quantity }}>
        <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
        <input type="submit" value={{ icon }}>
    </form>
{% endmacro %}

{% block content %}
<div class="cart">
    <h2>Cart</h2>
    {% if session.get('cart') %}
        <table>
            <tbody>
                {% for id, quantity in session['cart'].items() %}
                    {% set name = session['meta'][id]['name'] %}
                    {% set product = session['meta'][id]['product_id'] %}
                    <tr>
                        <td>{{ name }}</td>
                        <td class='cart--update-quantity-symbol'>{{ set_quantity('➖', id, name, product, quantity-1) }}</td>
                        <td class='cart--quantity'>{{ quantity }}</td>
                        <td class='cart--update-quantity-symbol'>{{ set_quantity('➕', id, name, product, quantity+1) }}</td>
                        <td>{{ '${:,.2f}'.format(session['meta'][id]['price']/100 * quantity) }} {{ set_quantity('🗑', id, name, 0) }}</td>
                    </tr>
                {% endfor %}
                <tr>
                    <td>Subtotal</td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td>{{ '${:,.2f}'.format(subtotal/100) }}</td>
                </tr>
            </tbody>
        </table>
        <a href="{{ url_for('shop.checkout') }}" class="go-checkout">Check Out</a>
    {% else %}
        <h2>Your cart is empty.</h2>
    {% endif %}
</div>
{% endblock %}

konbini/templates/shop/checkout.html
{% from "shop/_macros.html" import render_field_with_errors %}
{% extends 'layout.html' %}

{% block content %}
<div class="checkout">
    <h2>Checkout</h2>
    <h3>Shipping address</h3>
    {% if invalid_address %}
        <div class="checkout--error">We were unable to validate that address.</div>
    {% endif %}
    <form method="POST">
        {{ form.hidden_tag() }}
        {{ form.address.hidden_tag() }}
        {{ render_field_with_errors(form.name) }}
        {{ render_field_with_errors(form.address.line1) }}
        {{ render_field_with_errors(form.address.line2) }}
        <div class="column-3">
            {{ render_field_with_errors(form.address.city) }}
            {{ render_field_with_errors(form.address.state) }}
            {{ render_field_with_errors(form.address.postal_code) }}
        </div>
        <!-- <div class="column-2"> -->
            {# render_field_with_errors(form.address.country) #}
            {# render_field_with_errors(form.address.postal_code) #}
        <!-- </div> -->
        <div class="actions">
            <input type="submit" value="Save Address">
        </div>
    </form>
</div>
{% endblock %}

konbini/templates/shop/email.html
{% from "shop/_macros.html" import render_field_with_errors %}
{% extends 'layout.html' %}

{% block content %}
<div class="checkout">
    <h2>Checkout</h2>
    <h3>Email</h3>
    <form method="POST">
        {{ form.hidden_tag() }}
        {{ render_field_with_errors(form.email) }}
        <div class="actions">
            <input type="submit" value="Save Email">
        </div>
    </form>
</div>
{% endblock %}

konbini/templates/shop/index.html
{% extends 'layout.html' %}

{% block content %}
<h1>All</h1>
{% if not products %}
    <h2>No products</h2>
{% else %}
    <ul class="grid">
        {% for p in products %}
            <li class="item">
                <figure>
                    <a href="{{ url_for('shop.product', id=p.id[5:]) }}">
                        <img src="{{ p.images[0] }}" class="thumb" />
                    </a>
                </figure>
                <div class="justify-vertical">
                    <h2>
                        <a href="{{ url_for('shop.product', id=p.id[5:]) }}">
                            {{ p.name }}
                        </a>
                    </h2>
                    <div class="meta">
                        <div>{{ p.caption or p.metadata.caption }}</div>
                    </div>
                </div>
            </li>
        {% endfor %}
    </ul>
{% endif %}
{% endblock %}

konbini/templates/shop/layout.html
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <title>{{ config.SHOP_NAME }}</title>
  <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
  <link rel="icon" type="image/png" href="{{ url_for('static', filename='favicon/16.png') }}" sizes="16x16" />
  <link rel="icon" type="image/png" href="{{ url_for('static', filename='favicon/32.png') }}" sizes="32x32" />
  <link rel="icon" type="image/png" href="{{ url_for('static', filename='favicon/96.png') }}" sizes="96x96" />
</head>
<body>
    {% include "shop/_messages.html" %}
    <header>
        <div class="header--meta">
            <a href="{{ url_for('shop.index') }}"><img src="{{ url_for('static', filename='logo.svg') }}" alt="logo" title="logo" class="header--brand"></a>
        </div>
        <nav>
            <ul>
                {% set cart_size = session.get('cart', {}).values()|sum %}
                <li><a href="{{ url_for('shop.cart') }}">Cart{% if cart_size > 0 %} ({{ cart_size }}){% endif %}</a></li>
            </ul>
        </nav>
    </header>

    <main>
        {% block content %}
        {% endblock %}
    </main>
</body>
</html>

konbini/templates/shop/manage.html
{% from "shop/_macros.html" import render_field_with_errors %}
{% extends 'layout.html' %}

{% block content %}
<div class="checkout">
    <h2>Manage Subscription</h2>
    <p>Enter the email associated with your subscription below.</p>
    <form method="POST">
        {{ form.hidden_tag() }}
        {{ render_field_with_errors(form.email) }}
        <div class="actions">
            <input type="submit" value="Submit">
        </div>
    </form>
</div>
{% endblock %}

konbini/templates/shop/pay.html
{% extends 'layout.html' %}

{% block content %}
<div class="checkout">
    <h2>Review Order</h2>
    <h4>Items</h4>
    <div>
        <table>
            <tbody>
                {% for item in items %}
                    <tr>
                        <td>{{ item.name }}</td>
                        <td>{{ item.quantity or '' }}</td>
                        <td>{{ '${:,.2f}'.format((item.amount/100)*item.quantity) }}</td>
                    </tr>
                {% endfor %}
                <tr>
                    <td>Total</td>
                    <td></td>
                    <td>{{ '${:,.2f}'.format(total/100) }}</td>
                </tr>
            </tbody>
        </table>
    </div>
    <h4>Shipping to</h4>
    {% if address_changed %}
        <div class="checkout--warning">Your address was normalized to the one below. Please check that it's correct.</div>
    {% endif %}
    <div>
        <div>{{ shipping.name }}</div>
        <div>{{ shipping.address.line1 }}</div>
        {% if shipping.address.line2 %}
            <div>{{ shipping.address.line2 }}</div>
        {% endif %}
        <div>{{ shipping.address.city }}, {{ shipping.address.state }}</div>
        <div>{{ shipping.address.country }}, {{ shipping.address.postal_code }}</div>
    </div>
    <button id="js-pay">Pay</button>
</div>
{% include "shop/_stripe.html" %}
{% endblock %}

konbini/templates/shop/product.html
{% extends 'layout.html' %}

{% block content %}
<div class="product">
    <div class="product--gallery">
        {% for img in images %}
            <figure>
                <img src="{{ img }}" />
            </figure>
        {% endfor %}
    </div>
    <div class="product--info">
        <h1>{{ product.name }}</h1>
        <p>{{ product.description }}</p>
        <div class="product--skus">
            {% if skus|length == 0 and prices|length == 0 %}
                <div>Not currently available.</div>
            {% endif %}
            {% for sku in skus %}
                <div class="product--sku">
                    <form action='{{ url_for('shop.cart') }}' method='POST'>
                        <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
                        <input type='hidden' name='sku' value={{ sku.id }}>
                        <input type='hidden' name='name' value='{{ product.name }} - {{ sku.attributes.values()|join(', ') }}'>
                        <div class="sku">
                            <div>
                                <div>{{ sku.attributes.values()|join(', ') }}</div>
                                <div class="sku--price">{{ '${:,.2f}'.format(sku.price/100) }}</div>
                            </div>
                            {% if sku.in_stock %}
                                <input type="submit" value='Add to Cart'>
                            {% else %}
                                <input type="submit" disabled value='Out of Stock'>
                            {% endif %}
                        </div>
                    </form>
                </div>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}

konbini/templates/shop/sorry.html
{% extends 'layout.html' %}

{% block content %}
<div class="sorry">
    <h1>Sorry</h1>
    <h2>Certain items in your cart cannot be shipped internationally.</h2>
    <table>
    {% for p,q in products %}
      <tr>
        <td>{{p.name}}</td>
      </tr>
    {% endfor %}
    </table>
</div>
{% endblock %}

konbini/templates/shop/subscribe.html
{% extends 'layout.html' %}

{% block content %}
<div class="checkout checkout-plan">
    <h2>Review Order</h2>
    <h4>Subscription</h4>
    <table>
        <tbody>
            <tr>
                <td>{{ name }}</td>
                <td>{{ '${:,.2f}'.format(amount/100) }}</td>
            </tr>
            {% for item in line_items %}
                <tr>
                    <td>{{ item.name }}</td>
                    <td>{{ '${:,.2f}'.format(item.amount/100 * item.quantity) }}</td>
                </tr>
            {% endfor %}
            <tr>
                <td>Total</td>
                <td>{{ '${:,.2f}'.format(total/100) }}</td>
            </tr>
        </tbody>
    </table>

    {% if shipped %}
        <h4>Shipping to</h4>
        {% if address_changed %}
            <div class="checkout--warning">Your address was normalized to the one below. Please check that it's correct.</div>
        {% endif %}
        <div>
            <div>{{ address.name }}</div>
            <div>{{ address.line1 }}</div>
            {% if address.line2 %}
                <div>{{ address.line2 }}</div>
            {% endif %}
            <div>{{ address.city }}, {{ address.state }}</div>
            <div>{{ address.country }}, {{ address.postal_code }}</div>
        </div>
    {% endif %}
    <button id="js-pay">Pay</button>
</div>
{% include "shop/_stripe.html" %}
{% endblock %}