shop/routes.py
import math
import config
import stripe
import easypost
from flask_mail import Message
from .forms import CheckoutForm
from urllib.parse import urlparse, urljoin
from flask import Blueprint, render_template, redirect, request, session, abort, url_for, flash, current_app, jsonify

bp = Blueprint('main', __name__)

def send_email(to, subject, template, reply_to=config.MAIL_REPLY_TO, bcc=None, **kwargs):
    msg = Message(subject,
                body=render_template('email/{}.txt'.format(template), **kwargs),
                html=render_template('email/{}.html'.format(template), **kwargs),
                recipients=[to],
                reply_to=reply_to,
                bcc=bcc)
    current_app.mail.send(msg)

def is_in_stock(sku):
    inv = sku['inventory']
    if inv['type'] == 'bucket' and inv['value'] == 'out_of_stock':
        return False
    elif inv['type'] == 'finite' and inv['quantity'] == 0:
        return False
    return True

def is_safe_url(target):
    ref_url = urlparse(request.host_url)
    test_url = urlparse(urljoin(request.host_url, target))
    return test_url.scheme in ('http', 'https') and \
           ref_url.netloc == test_url.netloc


@bp.route('/')
@bp.route('/products')
def products():
    products = stripe.Product.list(limit=100, active=True, type='good')['data']
    if request.args.get('format') == 'json':
        return jsonify(results=products)
    else:
        return render_template('products.html', products=products)

@bp.route('/product/<id>')
def product(id):
    id = 'prod_{}'.format(id)
    product = stripe.Product.retrieve(id)
    if product is None or not product.active: abort(404)
    skus = stripe.SKU.list(limit=100, product=id, active=True)['data']
    images = set(product.images + [s.image for s in skus])
    for sku in skus:
        sku['in_stock'] = is_in_stock(sku)
    if request.args.get('format') == 'json':
        return jsonify(product=product, skus=skus, images=images)
    else:
        return render_template('product.html', product=product, skus=skus, images=images)

@bp.route('/plans')
def plans():
    plans = stripe.Product.list(limit=100, active=True, type='service')['data']
    if request.args.get('format') == 'json':
        return jsonify(results=plans)
    else:
        return render_template('plans.html', plans=plans)

@bp.route('/plans/<id>')
def plan(id):
    id = 'prod_{}'.format(id)
    product = stripe.Product.retrieve(id)
    if product is None or not product.active: abort(404)
    plans = stripe.Plan.list(limit=100, product=id, active=True)['data']
    if request.args.get('format') == 'json':
        return jsonify(product=product, plans=plans)
    else:
        return render_template('plan.html', product=product, plans=plans)

@bp.route('/cart', methods=['GET', 'POST'])
def cart():
    if request.method == 'GET':
        subtotal = sum((session['meta'][id]['price'] * q for id, q in session.get('cart', {}).items()), 0)
        return render_template('cart.html', subtotal=subtotal)

    name = request.form['name']
    sku_id = request.form['sku']
    quantity = request.form.get('quantity')
    if quantity is not None:
        quantity = int(quantity)

    if 'cart' not in session:
        session['cart'] = {}

    # If no quantity specified, add one
    if quantity is None:
        added = True
        session['cart'][sku_id] = session['cart'].get(sku_id, 0) + 1
    else:
        added = False
        session['cart'][sku_id] = quantity

    if 'meta' not in session:
        session['meta'] = {}

    # Delete item from cart if quantity is 0
    if quantity == 0:
        del session['cart'][sku_id]

    # Otherwise, update product info
    else:
        if sku_id.startswith('sku_'):
            sku = stripe.SKU.retrieve(sku_id)
            price = sku.price
            interval = None
        elif sku_id.startswith('plan_'):
            sku = stripe.Plan.retrieve(sku_id)
            price = sku.amount
            interval = sku.interval
        session['meta'][sku_id] = {
            'name': name,
            'price': price,
            'interval': interval
        }

    if added:
        flash('Added "{}" to cart.'.format(name), category='cart')
    else:
        flash('Cart updated.')

    if is_safe_url(request.referrer):
        return redirect(request.referrer)
    return redirect(url_for('main.products'))

@bp.route('/checkout', methods=['GET', 'POST'])
def checkout():
    if not session.get('cart'):
        return redirect(url_for('main.products'))

    form = CheckoutForm()
    if form.validate_on_submit():
        session['order'] = stripe.Order.create(
            currency='usd',
            items=[{
                'type': 'sku',
                'parent': sku_id,
                'quantity': quantity,
                'amount': session['meta'][sku_id]['price'],
                'description': session['meta'][sku_id]['name']
            } for sku_id, quantity in session['cart'].items()],
            shipping={
                'name': form.data['name'],
                'address': {k: form.data['address'][k] for k in
                    ['line1', 'line2', 'city', 'state', 'country', 'postal_code']}
            })
        return redirect(url_for('main.pay'))
    return render_template('checkout.html', form=form)

@bp.route('/checkout/pay')
def pay():
    if not session.get('order'):
        return redirect(url_for('main.cart'))

    session['stripe'] = stripe.checkout.Session.create(
        client_reference_id=session['order']['id'],
        payment_method_types=['card'],
        line_items=[{
            'name': session['meta'][sku_id]['name'],
            'amount': session['meta'][sku_id]['price'],
            'currency': 'usd',
            'quantity': quantity,
        } for sku_id, quantity in session['cart'].items()],
        success_url=url_for('main.checkout_success', _external=True),
        cancel_url=url_for('main.checkout_cancel', _external=True))
    return render_template('pay.html')

@bp.route('/checkout/success')
def checkout_success():
    for k in ['cart', 'plan', 'stripe', 'order']:
        if k in session: del session[k]
    return render_template('thanks.html')

@bp.route('/checkout/cancel')
def checkout_cancel():
    return 'cancelled' # TODO

@bp.route('/checkout/completed', methods=['POST'])
def checkout_completed_hook():
    payload = request.data
    sig_header = request.headers['Stripe-Signature']
    event = None

    try:
        event = stripe.Webhook.construct_event(
            payload, sig_header, config.STRIPE_WEBHOOK_SECRET
        )
    except ValueError:
        # Invalid payload
        return abort(400)
    except stripe.error.SignatureVerificationError:
        # Invalid signature
        return abort(400)

    # Handle the checkout.session.completed event
    if event['type'] == 'checkout.session.completed':
        session = event['data']['object']

        # If subscription is set,
        # assume that this is a checkout
        # for a subscription only
        if session['subscription'] is not None:
            return '', 200

        else:
            # Get associated order,
            # check its state
            order_id = session['client_reference_id']
            order = stripe.Order.retrieve(order_id)
            if order['status'] != 'created':
                return '', 200

            # print(session)
            # print(order)

            customer_id = session['customer']
            customer = stripe.Customer.retrieve(customer_id)
            customer_email = customer['email']

            # Create shipping label
            shipment = easypost.Shipment.retrieve(order.id)
            rate = next(r for r in shipment.rates if r['id'] == order.selected_shipping_method)
            shipment.buy(rate=rate)
            # print(shipment)

            items = [{
                'amount': i['amount'],
                'quantity': i['quantity'],
                'description': i['custom']['name']
            } for i in session['display_items']] + order['items'][2:]

            # Notify fulfillment person
            label_url = shipment.postage_label.label_url
            send_email(config.NEW_ORDER_RECIPIENT, 'New order placed', 'new_order', order=order, items=items, label_url=label_url)

            # Notify customer
            tracking_url = shipment.tracker.public_url
            send_email(customer_email, 'Thank you for your order', 'complete_order', order=order, items=items, tracking_url=tracking_url)

    return '', 200

@bp.route('/subscribe', methods=['GET', 'POST'])
def subscribe():
    if request.method == 'POST':
        name = request.form['name']
        price = request.form['price']
        plan_id = request.form['id']
        session['plan'] = {
            'name': name,
            'price': price,
            'plan_id': plan_id
        }

    if not session['plan']:
        return redirect(url_for('main.plans'))

    session['stripe'] = stripe.checkout.Session.create(
        payment_method_types=['card'],
        subscription_data={
            'items': [{
                'plan':  session['plan']['plan_id']
            }]
        },
        success_url=url_for('main.checkout_success', _external=True),
        cancel_url=url_for('main.checkout_cancel', _external=True))
    return render_template('subscribe.html', **session['plan'])


@bp.route('/checkout/tax', methods=['POST'])
def tax():
    data = request.get_json()
    order = data['order']

    addr = order['shipping']['address']
    tax = None
    for t in config.TAXES:
        if all(addr[k] == v for k, v in t['address'].items()):
            tax = t
            break

    if tax is not None:
        order_update = {
            'items': [{
                'parent': None,
                'type': 'tax',
                'description': 'Sales taxes',
                'amount': math.ceil(order['amount'] * tax['amount']),
                'currency': 'usd'
            }]
        }
    else:

shop/templates/_messages.html
{%- with messages = get_flashed_messages(with_categories=true) -%}
    <ul class="flashes" id="flashes">
    {% for category, message in messages %}
        {% if category == 'cart' %}
            <li>{{ message }} <a href="{{ url_for('main.checkout') }}" class="go-checkout">Checkout</a></li>
        {% else %}
            <li class="{{ category }}">{{ message }}</li>
        {% endif %}
    {% endfor %}
    </ul>
{%- endwith %}

shop/templates/cart.html
{% extends 'layout.html' %}

{% macro set_quantity(icon, sku, name, quantity) %}
    <form class="cart--update-quantity" action="{{ url_for('main.cart') }}" method="POST">
        <input type='hidden' name='sku' value={{ sku }}>
        <input type='hidden' name='name' value={{ name }}>
        <input type='hidden' name='quantity' value={{ quantity }}>
        <input type="submit" value={{ icon }}>
    </form>
{% endmacro %}

{% block content %}
<div class="cart">
    <h2>Cart</h2>
    {% if session.get('cart') %}
        <table>
            <tbody>
                {% for id, quantity in session['cart'].items() %}
                    {% set name = session['meta'][id]['name'] %}
                    <tr>
                        <td>{{ name }}</td>
                        <td class='cart--update-quantity-symbol'>{{ set_quantity('➖', id, name, quantity-1) }}</td>
                        <td class='cart--quantity'>{{ quantity }}</td>
                        <td class='cart--update-quantity-symbol'>{{ set_quantity('➕', id, name, quantity+1) }}</td>
                        <td>{{ '${:,.2f}'.format(session['meta'][id]['price']/100 * quantity) }} {{ set_quantity('🗑', id, name, 0) }}</td>
                    </tr>
                {% endfor %}
                <tr>
                    <td>Subtotal</td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td>{{ '${:,.2f}'.format(subtotal/100) }}</td>
                </tr>
            </tbody>
        </table>
        <a href="{{ url_for('main.checkout') }}" class="go-checkout">Checkout</a>
    {% else %}
        <h2>Your cart is empty.</h2>
    {% endif %}
</div>
{% endblock %}

shop/templates/layout.html
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <title>{{ config.NAME }} - shop</title>
  <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
  <link rel="icon" type="image/png" href="{{ url_for('static', filename='favicon/16.png') }}" sizes="16x16" />
  <link rel="icon" type="image/png" href="{{ url_for('static', filename='favicon/32.png') }}" sizes="32x32" />
  <link rel="icon" type="image/png" href="{{ url_for('static', filename='favicon/96.png') }}" sizes="96x96" />
</head>
<body>
    {% include "_messages.html" %}
    <header>
        <div class="header--meta">
            <a href="{{ url_for('main.products') }}"><img src="{{ url_for('static', filename='logo.svg') }}" alt="logo" title="logo" class="header--brand"></a>
        </div>
        <nav>
            <ul>
                <li><a href="{{ url_for('main.products') }}">Products</a></li>
                <li><a href="{{ url_for('main.plans') }}">Subscriptions</a></li>

                {% set cart_size = session.get('cart', {}).values()|sum %}
                <li><a href="{{ url_for('main.cart') }}">Cart{% if cart_size > 0 %} ({{ cart_size }}){% endif %}</a></li>
            </ul>
        </nav>
    </header>

    <main>
        {% block content %}
        {% endblock %}
    </main>
</body>
</html>

shop/templates/plan.html
{% extends 'layout.html' %}

{% block content %}
<div class="product">
    <div class="product--gallery">
        <figure>
            <img src="{{ product.metadata.image }}" />
        </figure>
    </div>

    <div class="product--info">
        <h1>{{ product.name }}</h1>
        <p>{{ product.metadata.description }}</p>
        <div class="product--skus">
            {% for plan in plans %}
                <div class="product--sku">
                    <form action='{{ url_for('main.subscribe') }}' method='POST'>
                        <input type='hidden' name='id' value={{ plan.id }}>
                        <input type='hidden' name='name' value='{{ product.name }} - {{ plan.nickname }}'>
                        <input type='hidden' name='price' value='{{ '${:,.2f}'.format(plan.amount/100) }}/{{ plan.interval }}'>
                        <div class="sku">
                            <div>
                                <div>{{ plan.nickname }}</div>
                                <div class="sku--price">{{ '${:,.2f}'.format(plan.amount/100) }}/{{ plan.interval }}</div>
                            </div>
                            <input type="submit" value='Subscribe'>
                        </div>
                    </form>
                </div>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}

shop/templates/plans.html
{% extends 'layout.html' %}

{% block content %}
<h1>Subscription Plans</h1>
{% if not plans %}
    <h2>No plans</h2>
{% else %}
    <ul class="grid">
        {% for p in plans %}
            <li class="item">
                <a href="{{ url_for('main.plan', id=p.id[5:]) }}">
                    <img src="{{ p.metadata.image }}" class="thumb" />
                </a>
                <div class="justify-vertical">
                    <h2>
                        <a href="{{ url_for('main.plan', id=p.id[5:]) }}">
                            {{ p.name }}
                        </a>
                    </h2>
                    <div class="meta">
                        <div>{{ p.metadata.caption }}</div>
                    </div>
                </div>
            </li>
        {% endfor %}
    </ul>
{% endif %}
{% endblock %}

shop/templates/product.html
{% extends 'layout.html' %}

{% block content %}
<div class="product">
    <div class="product--gallery">
        {% for img in images %}
            <figure>
                <img src="{{ img }}" />
            </figure>
        {% endfor %}
    </div>
    <div class="product--info">
        <h1>{{ product.name }}</h1>
        <p>{{ product.description }}</p>
        <div class="product--skus">
            {% for sku in skus %}
                <div class="product--sku">
                    <form action='{{ url_for('main.cart') }}' method='POST'>
                        <input type='hidden' name='sku' value={{ sku.id }}>
                        <input type='hidden' name='name' value='{{ product.name }} - {{ sku.attributes.values()|join(', ') }}'>
                        <div class="sku">
                            <div>
                                <div>{{ sku.attributes.values()|join(', ') }}</div>
                                <div class="sku--price">{{ '${:,.2f}'.format(sku.price/100) }}</div>
                            </div>
                            {% if sku.in_stock %}
                                <input type="submit" value='Add to Cart'>
                            {% else %}
                                <input type="submit" disabled value='Out of Stock'>
                            {% endif %}
                        </div>
                    </form>
                </div>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}

shop/templates/products.html
{% extends 'layout.html' %}

{% block content %}
<h1>Products</h1>
{% if not products %}
    <h2>No products</h2>
{% else %}
    <ul class="grid">
        {% for p in products %}
            <li class="item">
                <figure>
                    <a href="{{ url_for('main.product', id=p.id[5:]) }}">
                        <img src="{{ p.images[0] }}" class="thumb" />
                    </a>
                </figure>
                <div class="justify-vertical">
                    <h2>
                        <a href="{{ url_for('main.product', id=p.id[5:]) }}">
                            {{ p.name }}
                        </a>
                    </h2>
                    <div class="meta">
                        <div>{{ p.caption }}</div>
                    </div>
                </div>
            </li>
        {% endfor %}
    </ul>
{% endif %}
{% endblock %}